### ISSUE TITLE
To-do List 

### ISSUE THREAD

**Issue by pedroka-dev** [pedro-ca/Projeto-de-Redes-Exemplo#4]
- [x] Designar objetivos principais e escopo do projeto 
- [x] Discutir e atualizar os objetivos
- [x] Fazer pseudo-planta do predio

---
- [x] **Situação Física (Custeamento e expecificações)**
  - [x] Cabeamento
  - [x] Secretaria
  - [x] Direção 
  - [x] Corredores 1 e 2
  - [x] Corredores 3 e 4
  - [x] Laboratório de Informática
  - [x] Outros

---
- [x] **Situação Lógica (Topologia Packet Tracer e Protocolos)**
  - [x] Secretaria
  - [x] Direção 
  - [x] Corredores 1 e 2
  - [x] Corredores 3 e 4
  - [x] Laboratório de Informática
  - [x] Serviços
    - [x] DHCP
    - [x] WEB
    - [x] Server DNS
    - [x] SSH
    - [ ] LDAP
    - [ ] SAMBA
    - [x] E-MAIL (SMTP e IMAP);
  - [ ] Firewall
    - [ ] Interno
    - [ ] Externo
  - [ ] Rede cabeada separada logicamente da sem fio
  - [ ] Usuário e funcionarios realizam login na rede
  - [ ] Cota de 30gb para cada funcionário (30 funcionarios no total)
---
- [x] **Apresentação**
  - [x] Video

**Comment by JoaoMagal** [comment]
Referencias:
https://serverfault.com/questions/720422/should-i-use-a-server-to-do-multiple-services

**Comment by JoaoMagal** [comment]
Duvidas:
Distribuição dos serviços em servidores:
-É melhor deixar o web service em um server separado?
-É uma boa ideia usar um computador como um server?
-É uma boa ideia centralizar os serviços em um server só?
-Simulação física no packet tracer: é necessário?
-Qual a quantidade de clientes da rede?
